theme:
    name: material
    locale: en
    highlightjs: true
    custom_dir: overrides

markdown_extensions:
    toc:
        permalink: "#"
    admonition: {}


site_name: Kontent.ai GitHub docs
site_url: https://kontent-ai.github.io/wiki/