theme:
    name: material
    palette:
      scheme: slate
      primary: teal
    locale: en
    highlightjs: true
    custom_dir: overrides
    logo: kai-logo-symbol-white-rgb.svg

markdown_extensions:
    toc:
        permalink: "#"

site_name: Kontent.ai GitHub docs
site_url: https://kontent-ai.github.io/wiki/